[package]
name = "mem"
edition = "2024"

[dependencies]
bitflags = { version = "2.10.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["serde_derive", "derive"], default-features = false, optional = true }
postcard = { version = "1.1.3", optional = true, default-features = false, features = ["alloc"]  }

[features]
serde = ["dep:serde"]
std = []
postcard = ["dep:postcard"]
